version: "2"

services:
  app:
    environment: 
    - NODE_ENV=production
    - PORT=80
    container_name: app
    build: ./app
    ports:
      - "80:80"
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo:3.4.1
    ports:
      - "27017:27017"